### ISSUE TITLE
Botón

### ISSUE THREAD

**Issue by MariaJesusGomez** [M-daw/practica-git#1]
Tía, que el cliente solo quiere un botón, a ser preferible el bonito, el feo me lo sacas de ahí que es muy muy feo. A ver si lo arreglas, y rapidito que no tenemos todo el día.
Un besii <3

**Comment by rocio-soriano** [comment]
Mira tía, el botón feo solo tiene de feo el nombre. Lo voy a borrar pero lo borraré cuando yo quiera. Venga, besis, no me molestes más ;)
